import { Projects } from "@/types";

export const projects: Projects[] = [
  {
    id: 0,
    title: 'SAFE for Laboratories',
    description: 'AI and IoT-based smart attendance system, using RFiD and ESP32 for attendance recording and using YOLOv5 Object Detection Model to detect the use of personal protective equipment in real time before entering the laboratory. Using Flask API as an integrator between website and detection object model',
    tags: ['YOLOv5', 'Flask API', 'Deep Learning', 'Computer Vision', 'Pytorch', 'Object Detection'],
    githubLink: '',
    demoLink: '',
    image: '/projects/safe.png',
  },
  {
    id: 1,
    title: 'Mushroom Classification Website',
    description: 'This project involves the development of an AI model for the classification of poisonous and edible mushrooms, with a web-based implementation. The dataset used comes from kaggle, performing various exploratory data analysis to obtain a reliable machine learning model',
    tags: ['Machine Learning', 'Flask API', 'Supervised Learning', 'KNN', 'Classification'],
    githubLink: 'https://github.com/FaizAlfarisi/MushroomClassification',
    demoLink: '',
    image: '/projects/mushroom.png',
  },
  {
    id: 2,
    title: 'BISINDO Detection',
    description: 'This project focuses on developing a realtime BISINDO alphabet detection system utilizing the YOLOv8 architecture. Currently, the project has successfully reached the live testing stage and shows quite satisfactory results, opening up the potential for further development in supporting communication',
    tags: ['YOLOv8', 'Deep Learning', 'Computer Vision', 'Pytorch', 'Object Detection'],
    githubLink: '',
    demoLink: '',
    image: '/projects/bisindo.png',
  },
  {
    id: 3,
    title: 'Bank Transaction EDA for Fraud Detection',
    description: 'Exploratory data analysis of bank transaction datasets such as descriptive statistics and data visualization to get a detailed look of transactional behavior and financial activity patterns. Moreover, clustering with machine learning models was also performed to show the fraud transactions.',
    tags: ['Python', 'Pandas', 'Numpy', 'Matplotlib', 'Data Analyst', 'Clustering', 'K-Means'],
    githubLink: '',
    demoLink: '',
    image: '/projects/clustering.png',
  },
  {
    id: 4,
    title: 'E-Commerce Kacang Pedes Singo',
    description: 'This project involves the development of an e-commerce website for Kacang Pedes Singo using PHP, PHPmyAdmin, HTML, CSS, and . This website is designed to facilitate product sales, with an attractive appearance and features that support online transactions efficiently.',
    tags: ['PHP', 'MySQL', 'HTML', 'CSS'],
    githubLink: '',
    demoLink: '',
    image: '/projects/kacangsingo.png',
  },
  {
    id: 5,
    title: 'SieR-Te',
    description: 'SieR-Te is a web-based School Information System built with Go (Fiber) and PostgreSQL to streamline school administration. It supports modules for student data, academic records, announcements, and attendance. With a focus on clean RESTful APIs and scalable performance, the system aims to enhance operational efficiency and user experience in educational environments.',
    tags: ['GO', 'Go Fiber', 'GORM', 'REST API', 'PostgreSQL', 'Next.js', 'TailwindCSS'],
    githubLink: '',
    demoLink: '',
    image: '/projects/sierte.png',
  },
  {
    id: 6,
    title: 'Singosari Fitness Web App',
    description: 'Creating a website for Singosari Fitness that focuses on developing the back end. The development starts from analysis and needs and planning, ERD preparation, database creation, CRUD implementation page, to features for user needs.',
    tags: ['PHP', 'MySQL', 'HTML', 'CSS'],
    githubLink: '',
    demoLink: '',
    image: '/projects/singogym.png',
  },
]